services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cleanenergy
      POSTGRES_DB: cleanenergy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cleanenergy"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:cleanenergy@postgres:5432/cleanenergy"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run dev"]

volumes:
  postgres_data: